# Generated by Django 4.1.1 on 2022-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Выберите изображение', upload_to='recipes/images/', verbose_name='Изображение'),
        ),
    ]
