# Generated by Django 4.1.1 on 2022-10-05 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_cart_user_alter_follow_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.SmallIntegerField(help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления (минуты)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(blank=True, help_text='Укажите количество ингредиента', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Введите цветовой HEX-код тега', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='#([\\da-fA-F]{2})([\\da-fA-F]{2})([\\da-fA-F]{2})')], verbose_name='Цвет тега'),
        ),
    ]
