# Generated by Django 4.1.1 on 2022-10-05 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Введите цветовой HEX-код тега', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='^#([\\da-fA-F][\\da-fA-F][\\da-fA-F]){1,2}$')], verbose_name='Цвет тега'),
        ),
    ]
