# Generated by Django 2.2.28 on 2022-09-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220918_0737'),
    ]

    operations = [
    ]
